### ISSUE TITLE
Add "Road to riches" CSV option

### ISSUE THREAD

**Issue by ravensergio** [Numerlor/Auto_Neutron#32]
Hi . This is very useful in VR, thank you. I made my trip to Colonia with the tool, flawless.
I hope that some day we can have Spansh "Road to riches" included, so we can hop in the next system the same as we did with neutron plotter. For now, it looks like the loaded CSV is "invalid", so it doesn't work with it.
Thank You the tool is great for VR!

**Comment by Numerlor** [comment]
How do you envision this would look like? The current layout of the app and the overall working of it only allows systems themselves to be plotted and jumped to. Would the road to riches plotter simply add the systems without bodies, or should the bodies also be on display? I'm somewhat unfamiliar with the game as I don't remember much so I'm not sure whether copying body names would be useful

**Comment by ravensergio** [comment]
Thanks for responding. Indeed the Riches plotter has also bodies column,  I was thinking just let us import the csv made in Spanish,  and same as the neutron plotter just auto copy the next system. For the bodies worth scanning we can use other tools,  like EDDI that already tells me via SaPi voice what bodies are worth mapping. For VR this would be great also,  no alt tabbing needed after I'm done mapping the bodies. Thanks
