### ISSUE TITLE
ucrtbase.dll error 

### ISSUE THREAD

**Issue by SweetyVolty** [Numerlor/Auto_Neutron#4]
![pr1DLtZAVR](https://user-images.githubusercontent.com/36844988/80999700-c495d080-8e4d-11ea-846f-4e9a2641b47a.jpg)

As seen above.

**Comment by Numerlor** [comment]
Made a new release that should fix it, let me know if it does not.

**Comment by SweetyVolty** [comment]
oh thanks that seems to working out because didn't gave any errors at startup this time <3
