### ISSUE TITLE
update_script() missing 1 required positional argument: 'script'

### ISSUE THREAD

**Issue by Delrynn** [Numerlor/Auto_Neutron#5]
Using Python 3.6.2, all prereqs installed successfully, Windows 10 1909. I've tried running the tool as an administrator. Auto-copy works fine. CSV, neutron-plotter, and load-last work fine.

When I try to view and close the settings. I get "TypeError: update_script() missing 1 required positional argument: 'script'". It doesn't matter if changes are made or not. It looks like the settings are applied/saved, so this is more of an annoyance than anything.

Screenshot of powershell console, and error attached.
![XxnmMpL](https://user-images.githubusercontent.com/33699600/89193533-1d235980-d574-11ea-849a-55cbeaacb646.png)

**Comment by Numerlor** [comment]
Fixed in 5222ae4c123b2dbfe9660d2f4043946463bbbe5b
