### ISSUE TITLE
calculations for sco drives are a bit off

### ISSUE THREAD

**Issue by loekalive** [Numerlor/Auto_Neutron#50]
I'm not certain enough how exactly interaction between Auto_Neutron and spansh.co.uk works with regards to the jump range calculations. Therefore, this issue might need to be redirected towards spansh. 

The issue is this: When I use galaxy plotter in Auto_Neutron, the available jump range gets overestimated.

In my situation with a light weighted Anaconda with a 6A SCO FSD engineered with long range and mass manager, 96T of fuel and a full 32T cargo hold, about 7T of cargo needs to be jettisoned to actually be able to make the calculated jumps.

Workaround: Jettisoning said cargo will help, but it also causes the fuel consumed on shorter jumps to be less than calculated. This causes the total mass to remain higher than calculated, which causes the jump range near the end of the fuel tank to be shorter than calculated.

Anyway, I'm happy to be able to use Auto_Neutron again. I'm not entirely certain how I can best help to figure out a good solution for this issue. Suggestions are welcome, I'm happy to try and help.

**Comment by Numerlor** [comment]
The range for the galaxy plotter is calculated on spansh's side so not sure what the issue could be if the values are right. e.g. for [this ship](https://www.edsm.net/en/user/fleet/id/60525/cmdr/Numerlor/ship/sId/46/sType/128839281) (with a 5A SCO FSD) the request sends over
```json
{
  "source": "Fuelum",
  "destination": "Fular",
  "is_supercharged": 0,
  "use_supercharge": 0,
  "use_injections": 0,
  "exclude_secondary": 0,
  "fuel_power": 2.45,
  "fuel_multiplier": 0.012,
  "optimal_mass": 1175,
  "base_mass": 337.743007,
  "tank_size": 32,
  "internal_tank_size": 0.63,
  "max_fuel_per_jump": 5.2,
  "range_boost": 10.5,
  "cargo": 1
}
```


But when looking up things on the wiki I also found out that class constants are different for the SCO FSDs which are used to calculate the range on the neutron plotter, though even with those fixed it's a bit off so I'll need to look more in depth there.

I can hop on the IRC if you want to discuss it, no idea what's up with the galaxy plotter, maybe it's also using wrong constants on the galaxy plotter like Auto_Neutron does when calculating its own range?

**Comment by Numerlor** [comment]
Also does the range seem correct with a normal FSD? Just to know whether that's the cause

**Comment by loekalive** [comment]
> Also does the range seem correct with a normal FSD? Just to know whether that's the cause

Just tested with a normal 6A FSD engineered with long range and mass manager and for this setup the calculations are spot on.

I'm happy to do some leg work if needed to figure this out. Not sure what would help though, just let me know. If you like we can (slow) chat on irc. I'm always logged on, but often afk. I'll keep an eye out for you.

**Comment by Numerlor** [comment]
Should work now, realised it's sending the constant to spansh so it was working after that fix just didn't notice it in the routes I tried
