### ISSUE TITLE
Feature Request: Allow settings changes if ED is not running

### ISSUE THREAD

**Issue by Delrynn** [Numerlor/Auto_Neutron#7]
If ED is not running, after plotting a route, Auto Neutron will say "Game shut down", and allow you to:

1. Load a journal resulting in the same message
2. Save the current route, then close
3. Quit Auto Neutron
4. Close the 'Game shut down' window, but not be able to interact with the Auto Neutron window for the most part.

It would be nice to be able to edit settings via the settings menu while ED is not running.

I tried recording the behavior, but Windows DVR didn't pick up the pop up windows. You can see at the end me trying to get the right-click menu to appear after going with option 4.

https://user-images.githubusercontent.com/33699600/103805300-63984b00-5021-11eb-8a43-7428e78337a1.mp4

**Comment by Numerlor** [comment]
The behaviour was there to prevent issue from trying to move the route index and create a new ahk script after the route reached the end; I'm not sure if it's still present or what the original issue was at all but I'd like to get #6 merged before changing it much as it'll redesign most of the logic behind it and the windows. 
Unfortunately I currently don't have the motivation nor the time to work on this project so any non critical changes most probably won't come soon

**Comment by Numerlor** [comment]
should work fine with the new release, the context menu is now always available and journal is checked before a new route is made
